### ISSUE TITLE
Rename to promise-timer

### ISSUE THREAD

**Issue by clue** [clue/php-promise-timeout#11]
After talking to @jsor about #2 we agree that the packge name should be changed.

The package name should be "promise-timer" instead of "promise-timeout", as only a single function actually deals with timing out promises.

Accordingly, the namespace should be changed from "Promise\Timeout" to "Promise\Timer" (see also #10).

```
Timeout\await() => Timeout\timeout() => Timer\timeout() (see also #10)
Timeout\resolve() => Timer\resolve()
Timeout\reject() => Timer\reject()
```

**Comment by jsor** [comment]
:+1:
